### ISSUE TITLE
Remove 'Scroll to Bottom' from import as service does not support it

### ISSUE THREAD

**Issue by atopper** [adobe/helix-labs-website#41]
As per https://github.com/adobe/spacecat-api-service/pull/487#discussion_r1752547565, the option is not used.

### Expected Behaviour
Only have the "Scroll to Bottom" checkbox if the service uses it.

### Actual Behaviour
Apparently, the input is ignored, so do not present it to the user.

### Reproduce Scenario (including but not limited to)
Run imports with it on and off - any differences?

**Comment by atopper** [comment]
The flag is still mentioned here ([main code](https://github.com/adobe/spacecat-api-service/blob/main/docs/openapi/schemas.yaml#L1264)), so hesitating to pull it out too quickly.

**Comment by atopper** [comment]
Looks like both `scrollToBottom` and `customHeaders` are not (yet?) supported by the service:
https://github.com/adobe/spacecat-api-service/pull/494

**Comment by arumsey** [comment]
> Looks like both `scrollToBottom` and `customHeaders` are not (yet? [Jira](https://jira.corp.adobe.com/browse/SITES-24434)) supported by the service: [adobe/spacecat-api-service#494](https://github.com/adobe/spacecat-api-service/pull/494)

`customHeaders` is no longer included in `options` object but as its own object instead which is already supported by the Bulk Import UI AFAIK.

**Comment by arumsey** [comment]
@atopper The only checkbox that should be exposed is `enableJavascript` then?

**Comment by atopper** [comment]
Since 1 checkbox in 'options' looks weird, I suggest moving 'timeout' to the Options as well (technically they make up the 'options' object):
![image](https://github.com/user-attachments/assets/d3c0d674-2a54-41dd-8bbc-4bbe7c102cf3)
