### ISSUE TITLE
Image Audit 3000 image limit

### ISSUE THREAD

**Issue by cgoudie** [adobe/helix-labs-website#70]
Image Audit can't handle sites with more than about 3000 images without failing with an error 5, meaning too many images in the dom.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the code to load images in smaller batches and implement a pagination-like approach to handle sites with a large number of images. This should prevent the DOM from being overwhelmed and avoid the error 5 failure.

You can review changes in this commit: https://github.com/jjyutm4532/adobe-helix-labs-website-70/commit/783f15bf7b098d4bb22f3e5dc4fdd367c7aeafb5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
